### ISSUE TITLE
Dummy TTY sends characters to 0x801ffbb8 in 4-byte FIFO

### ISSUE THREAD

**Issue by norepimorphism** [psx-spx/psx-spx.github.io#35]
Hi,

In [this section](https://psx-spx.consoledev.net/kernelbios/#c1bh-kernelredirectttyflag-ps2-ttyflag1-causes-systemerror), it is stated that "the latter [parameter value] sends any std_out to nowhere". However, it does send it somewhere, as far as I can tell&mdash;to program address `0x801ffbb8`; this is at the very end of Main RAM. 32-bit writes are made to this address, where the value of each character is stored in the least significant byte. It is sent as if there is a LIFO (last in, first out) with a capacity of four bytes at the receiving end; that is, it sends bytes in the following order: 4th, 3rd, 2nd, 1st, 8th, 7th, 6th, 5th, and so on.

In a PSX emulator I'm writing, by catching writes to this address and storing them in a LIFO, flushing it every four characters, I see the following on boot:

```

PS-X Realtime Kernel Ver.2.5
Copyright 1993,1994 (C) Sony Computer Entertainment Inc.
```

I think this is more-or-less what I would see if I did a DUART patch.

**Comment by nicolasnoble** [comment]
This address is in the stack. Yes, the value will show up in the callstack as you're enabling a codepath that will have to respect ABI and this may include saving registers in the stack.

But (1) I would highly recommend against any sort of patch because it's very version based and would prevent custom bioses from running like https://github.com/grumpycoders/pcsx-redux/tree/main/src/mips/openbios and (2) relying on this very specific address in memory won't work as the stack grows with other callstacks. You've found the exact stack location in the stack for this exact printf, but the next printf will likely be further down, or maybe up, into the stack.

All in all, you'd be a lot better off intercepting the kernel calls themselves. You've linked to a section to the description of those calls. They are stable across all revisions of the bios because they are public APIs all games can use. You simply need to monitor when the execution reaches the addresses 0xa0, 0xb0, or 0xc0, and inspect the contents of the register `$t1`. Having a full kernel monitor can be useful, but you may also only focus on only the functions for printing messages in order to have debugging output.

Here's some examples:

https://github.com/grumpycoders/pcsx-redux/blob/main/src/core/kernellog.cc
https://github.com/grumpycoders/pcsx-redux/blob/main/src/core/r3000a.h#L389-L481

I'll go ahead and close this issue because the original wording talks about the hardware. There is indeed no DUART hardware, and on the real PS1 hardware, enabling TTY will simply be the same as screaming into an electronic void.

**Comment by norepimorphism** [comment]
First of all, thanks for pointing me to an open-source BIOS! I was actually looking for one earlier today, and I'm surprised that one exists.

Second, thanks for clearing it up. I feel a little silly for making this issue now; I forgot that's where the stack is, haha! It was easy to forget for me as the stack pointer is a general-purpose register entirely managed by software. (I come from a background of writing 8-bit emulators where the emulator is responsible for initializing and manipulating the stack pointer.) Knowing that it's the stack answers all of my questions. I was hoping there was *some* memory location into which the dummy TTY stores characters, but if none exists, you are definitely correct that the best course of action is simply to intercept the kernel calls.

Thanks for the help!

**Comment by nicolasnoble** [comment]
No worries at all~ glad I can be of help!

If you're into emulation development, I would recommend joining the emudev Discord server: https://discord.gg/dkmJAes

There's also more Discord resources mentioned in the main README of this repository that are more playstation-focused.

Or feel free to use the Discussion tab if you want to ask more questions too, but the audience will be much more limited.
